version: "3.5"

services:
  vbgs:
    image: vikebot/vbgs
    expose:
      - 2400
    ports:
      - "2400:2400"
    networks:
      - vbgs-fluentd-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: {{.ID}}
  
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluented/etc
    networks:
      - fluentd-elastic-network
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - fluentd-elastic-network
      - elastic-kibana-network

  kibana:
    image: kibana
    networks:
      - elastic-kibana-network

networks:
  vbgs-fluentd-network:
    driver: bridge
  fluentd-elastic-network:
    driver: bridge
  elastic-kibana-network:
    driver: bridge
